// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNGuSq_6hihgV8YrkOzbvlVOJEZJjOFg8',
    appId: '1:468849573285:web:1409d2d35f1723beadfc4c',
    messagingSenderId: '468849573285',
    projectId: 'flutterauth-78b97',
    authDomain: 'flutterauth-78b97.firebaseapp.com',
    storageBucket: 'flutterauth-78b97.appspot.com',
    measurementId: 'G-NP8Y64TL46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHrEvSie8s5JDnxyoJ2VNuW1jYlP2dZoY',
    appId: '1:468849573285:android:4179d955bb273ce2adfc4c',
    messagingSenderId: '468849573285',
    projectId: 'flutterauth-78b97',
    storageBucket: 'flutterauth-78b97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIV8aDY51rbszv1jZPS4IPHcFezFxQaU0',
    appId: '1:468849573285:ios:fb84418b9abaf0cbadfc4c',
    messagingSenderId: '468849573285',
    projectId: 'flutterauth-78b97',
    storageBucket: 'flutterauth-78b97.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIV8aDY51rbszv1jZPS4IPHcFezFxQaU0',
    appId: '1:468849573285:ios:0d6e3253a1f6c3f1adfc4c',
    messagingSenderId: '468849573285',
    projectId: 'flutterauth-78b97',
    storageBucket: 'flutterauth-78b97.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
